### PR TITLE
#3: notify when pledges expire (closes #3)

### LINKED ISSUE #3: notify when pledges expire
## stories
- as performer | requester, I want to be notified when a pledge expires so as to investigate what went wrong and fix the problem, or delete it if it was actually completed

## requirements
- send 1 notification to both performer and requester to notify that a pledge just expired
  - be within a few minutes of expiry date, super precision is not necessary
  - never send the same notification twice ;-)
- **manage migration of DB for new column**

## specs
- add a column `expiredNotificationSent` in the `pledges` table, default to false
- every 1 minute (`setInterval`), search for pledges where `expiredNotificationSent` is false and `deadline` is in the past
- notify and set `expiredNotificationSent` to true

## misc

{optional: other useful info}

### PR DESCRIPTION
**Pull request by lucacioria**
Issue #3

### tests performed
- tested locally with ngrok, notification for requester arrived:
image
  - notification for performer was sent to @FrancescoCioria (did you receive it?)

- migration tested locally on a version 1 DB
  - tested migration from v1 to v2
    - also with populated tables
  - tested generating a DB from scratch (new install of v2)
  - tested running on a v2 (stop & start after migrating)

### CODE REVIEW

File: src/db.js [hunk 1]
```diff
@@ -10,11 +10,44 @@ const createTables = () => {
...
+      expiredNotificationSent BOOLEAN NOT NULL DEFAULT 0,
       created_at INTEGER NOT NULL
-    )`
+    );`
   );
 };
 
+const migrateIfNeeded = async () => {
+  // if there is no table schemaVersions, currentVersion is 1
+  let currentVersion = (await db.get(`
```
Comment (FrancescoCioria) [inline src/db.js]: I find this logic confusing, I understood it only thanks to the comments.
Wouldn't it better to add a variable `hasSchemaVersionTable` and make `currentVersion` a `const`?

```js
const hasSchemaVersionsTable = !!(await db.get(`
  SELECT 1 FROM sqlite_master WHERE name ='schemaVersions' and type='table';
 `);

const currentVersion = hasSchemaVersionsTable ?
  (await db.get(`SELECT max(version) as v FROM schemaVersions`)).v : 
  1;
```

File: src/index.js [hunk 2]
```diff
@@ -98,4 +101,17 @@ app.get('/deletePledge/:pledgeId', async ({ params: { pledgeId } }, res) => {
   }
 });
 
+async function findNewNotifications() {
+  // notify for pledges that have expired
+  const expiredPledges = await db.findAllPledgesExpiredToNotify();
+  expiredPledges.map(async p => {
```
Comment (FrancescoCioria) [inline src/index.js:107]: just a note (in this case it shouldn't be an issue): putting the `async/await` inside the map function doesn't mean you're waiting for it so `findNewNotifications` returns before the map has actually ended.

As I already said, as the interval is set for 1min, it's not an issue in this case

File: src/index.js [hunk 3]
```diff
@@ -98,4 +101,17 @@ app.get('/deletePledge/:pledgeId', async ({ params: { pledgeId } }, res) => {
...
+    await postOnSlackMultipleChannels({
```
Comment (FrancescoCioria) [inline src/index.js:108]: this `await` is not working: `postOnSlackMultipleChannels` returns an array of promises and `await` only waits for promises. If you want to wait for every promise inside the array to be complete you have to use `Pomise.all` which wraps the array with another promise wwhich completes only when every single promise inside the array is complete.

```js
const postOnSlackMultipleChannels =
  (json, channels) => Promise.all(channels.map(c => postOnSlack({ channel: c, ...json })));
```

File: src/index.js [hunk 4]
```diff
@@ -98,4 +101,17 @@ app.get('/deletePledge/:pledgeId', async ({ params: { pledgeId } }, res) => {
...
+      text: `pledge ${p.content} expired just now`
+    }, [p.requester, p.performer]);
+    await db.setExpiredNotificationAsSentOnPledge(p.id);
+  });
+}
+
+setInterval(findNewNotifications, 5 * 1000);
```
Comment (FrancescoCioria) [inline src/index.js]: hey, this isn't a minute! it's only 5 seconds....
This may be an issue as you're not waiting for `findNewNotifications` to actually finish: `expiredPledges.map(...` returns an array of promises which is not `await`ed by anyone.

If it takes longer than 5 seconds to complete `findNewNotifications` you'll eventually send multiple notifications (or may not, I don't know how the `db` works)

File: src/db.js (hunk 1 above)
Comment (lucacioria) [reply src/db.js]: good suggestion, I wanted to do something like this but failed and used a `let`, this is much better

File: src/index.js (hunk 2 above)
Comment (lucacioria) [reply src/index.js:107]: ok cool I didn't really understand this, now it makes more sense

File: src/index.js (hunk 3 above)
Comment (lucacioria) [reply src/index.js:108]: ok thanks

File: src/index.js (hunk 4 above)
Comment (lucacioria) [reply src/index.js]: oops, it was just for testing quickly and I forgot it there
